import { GameLevel } from '@/types/game';

export const initialLevels: GameLevel[] = [
  {
    id: 'level1',
    name: 'Forest Friends',
    difficulty: 'easy',
    correctAnimalId: 'fox',
    completed: false,
    animals: [
      {
        id: 'fox',
        name: 'Fox',
        pawPrintImage: 'https://images.pexels.com/photos/3550969/pexels-photo-3550969.jpeg',
        animalImage: 'https://images.pexels.com/photos/2326936/pexels-photo-2326936.jpeg',
        clues: [
          'This animal has a bushy tail',
          'This animal has pointy ears',
          'This animal is known for being clever',
          'This animal has reddish-orange fur',
        ],
        fact: 'Foxes are part of the Canidae family, which means they're related to wolves, jackals, and dogs. They're also the only member of the Canidae family that can climb trees!',
        habitat: 'forest',
        eliminated: false,
      },
      {
        id: 'bear',
        name: 'Bear',
        pawPrintImage: 'https://images.pexels.com/photos/158109/kodiak-brown-bear-adult-portrait-wildlife-158109.jpeg',
        animalImage: 'https://images.pexels.com/photos/158109/kodiak-brown-bear-adult-portrait-wildlife-158109.jpeg',
        clues: [
          'This animal hibernates in winter',
          'This animal is very large',
          'This animal loves honey',
          'This animal has sharp claws',
        ],
        fact: 'Bears have excellent memory, large brains, and are capable of using tools. They can run up to 37 miles per hour!',
        habitat: 'forest',
        eliminated: false,
      },
      {
        id: 'rabbit',
        name: 'Rabbit',
        pawPrintImage: 'https://images.pexels.com/photos/326012/pexels-photo-326012.jpeg',
        animalImage: 'https://images.pexels.com/photos/326012/pexels-photo-326012.jpeg',
        clues: [
          'This animal has long ears',
          'This animal hops to move around',
          'This animal eats carrots',
          'This animal has a short fluffy tail',
        ],
        fact: 'Rabbits can jump up to 3 feet high and 9 feet forward in a single bound! Their teeth never stop growing throughout their entire life.',
        habitat: 'forest',
        eliminated: false,
      },
      {
        id: 'deer',
        name: 'Deer',
        pawPrintImage: 'https://images.pexels.com/photos/33321/deer-fawn-animal-mammal.jpg',
        animalImage: 'https://images.pexels.com/photos/33321/deer-fawn-animal-mammal.jpg',
        clues: [
          'This animal has antlers',
          'This animal can jump very high',
          'This animal is very fast',
          'Baby animals of this type are called fawns',
        ],
        fact: 'Deer can jump up to 10 feet high and run at speeds of up to 35 miles per hour. Their eyes are on the sides of their head, giving them a 310-degree view!',
        habitat: 'forest',
        eliminated: false,
      },
    ],
  },
  {
    id: 'level2',
    name: 'Safari Adventure',
    difficulty: 'normal',
    correctAnimalId: 'tiger',
    completed: false,
    animals: [
      {
        id: 'tiger',
        name: 'Tiger',
        pawPrintImage: 'https://images.pexels.com/photos/40535/tiger-animal-zoo-stripes-40535.jpeg',
        animalImage: 'https://images.pexels.com/photos/40535/tiger-animal-zoo-stripes-40535.jpeg',
        clues: [
          'This animal has stripes',
          'This animal is a big cat',
          'This animal is orange and black',
          'This animal is an excellent swimmer',
        ],
        fact: 'Tigers are the largest wild cats in the world. Unlike most cats, tigers love water and are excellent swimmers. Each tiger's stripes are unique, like human fingerprints!',
        habitat: 'jungle',
        eliminated: false,
      },
      {
        id: 'elephant',
        name: 'Elephant',
        pawPrintImage: 'https://images.pexels.com/photos/66898/elephant-cub-tsavo-kenya-66898.jpeg',
        animalImage: 'https://images.pexels.com/photos/66898/elephant-cub-tsavo-kenya-66898.jpeg',
        clues: [
          'This animal has a long trunk',
          'This animal is the largest land mammal',
          'This animal has big ears',
          'This animal has tusks',
        ],
        fact: 'Elephants are the largest land animals on Earth. They have amazing memories and can live up to 70 years. Their trunks contain over 40,000 muscles!',
        habitat: 'savanna',
        eliminated: false,
      },
      {
        id: 'giraffe',
        name: 'Giraffe',
        pawPrintImage: 'https://images.pexels.com/photos/802112/pexels-photo-802112.jpeg',
        animalImage: 'https://images.pexels.com/photos/802112/pexels-photo-802112.jpeg',
        clues: [
          'This animal has a very long neck',
          'This animal is the tallest land animal',
          'This animal has spots',
          'This animal eats leaves from tall trees',
        ],
        fact: 'Giraffes are the tallest living animals in the world, with males reaching up to 18 feet tall. Their tongues can be up to 21 inches long and are dark bluish-purple in color!',
        habitat: 'savanna',
        eliminated: false,
      },
      {
        id: 'lion',
        name: 'Lion',
        pawPrintImage: 'https://images.pexels.com/photos/36843/lion-panthera-leo-animal-portrait.jpg',
        animalImage: 'https://images.pexels.com/photos/36843/lion-panthera-leo-animal-portrait.jpg',
        clues: [
          'This animal is called the king of the jungle',
          'Male animals of this type have a mane',
          'This animal lives in a pride',
          'This animal roars loudly',
        ],
        fact: 'Lions are the only cats that live in groups called prides. A lion's roar can be heard from 5 miles away, and they can sleep up to 20 hours a day!',
        habitat: 'savanna',
        eliminated: false,
      },
    ],
  },
  {
    id: 'level3',
    name: 'Ocean Explorers',
    difficulty: 'hard',
    correctAnimalId: 'dolphin',
    completed: false,
    animals: [
      {
        id: 'dolphin',
        name: 'Dolphin',
        pawPrintImage: 'https://images.pexels.com/photos/64219/dolphin-marine-mammals-water-sea-64219.jpeg',
        animalImage: 'https://images.pexels.com/photos/64219/dolphin-marine-mammals-water-sea-64219.jpeg',
        clues: [
          'This animal is very intelligent',
          'This animal uses echolocation',
          'This animal is a mammal that lives in water',
          'This animal breathes air through a blowhole',
        ],
        fact: 'Dolphins are extremely intelligent marine mammals. They can recognize themselves in mirrors, solve problems, and even have unique whistles that serve as names!',
        habitat: 'ocean',
        eliminated: false,
      },
      {
        id: 'shark',
        name: 'Shark',
        pawPrintImage: 'https://images.pexels.com/photos/726478/pexels-photo-726478.jpeg',
        animalImage: 'https://images.pexels.com/photos/726478/pexels-photo-726478.jpeg',
        clues: [
          'This animal has many sharp teeth',
          'This animal has multiple rows of teeth that replace old ones',
          'This animal has a fin on its back',
          'This animal is a fish with a cartilage skeleton',
        ],
        fact: 'Sharks have been around for over 450 million years, even before dinosaurs! They can have up to 300 teeth at once, and some species never stop growing new teeth their entire lives.',
        habitat: 'ocean',
        eliminated: false,
      },
      {
        id: 'octopus',
        name: 'Octopus',
        pawPrintImage: 'https://images.pexels.com/photos/752673/pexels-photo-752673.jpeg',
        animalImage: 'https://images.pexels.com/photos/752673/pexels-photo-752673.jpeg',
        clues: [
          'This animal has eight arms',
          'This animal can change color',
          'This animal releases ink when threatened',
          'This animal has three hearts',
        ],
        fact: 'Octopuses are incredibly intelligent and can solve complex puzzles. They have three hearts, blue blood, and can change both the color and texture of their skin in less than a second!',
        habitat: 'ocean',
        eliminated: false,
      },
      {
        id: 'turtle',
        name: 'Sea Turtle',
        pawPrintImage: 'https://images.pexels.com/photos/847393/pexels-photo-847393.jpeg',
        animalImage: 'https://images.pexels.com/photos/847393/pexels-photo-847393.jpeg',
        clues: [
          'This animal has a hard shell',
          'This animal lays eggs on beaches',
          'This animal can live for over 100 years',
          'This animal has flippers instead of legs',
        ],
        fact: 'Sea turtles have been around for over 100 million years, surviving the extinction of dinosaurs. They can hold their breath underwater for hours and navigate using Earth's magnetic field!',
        habitat: 'ocean',
        eliminated: false,
      },
    ],
  },
];